### ISSUE TITLE
minimize parking space calculator

### ISSUE THREAD

**Issue by jsammer** [SCCapstone/ADAUSC#31]
The text blocks on the calculator screen are able to be minimized and made small only showing the title. However the calculator part isn't able to be made small. So when the user wants to go read one of the text blocks, they have to open and then scroll farther down to be able to view it. 

make the calculator able to be minimized like the text blocks.

**Comment by dkbrookins** [comment]
The calculator can't be minimized because it isn't a single view like the other text blocks. Instead, it's multiple elements.
